<?php
/**
 * Udevix
 *
 * @author     UdevixTeam <udevix@gmail.com>
 * @copyright  Copyright (c) 2015-2016 Udevix
 */
?>

<?php
/**
 * @var Udevix_GoogleTagManager_Block_Adwords_Conversion $this
 * @var Udevix_GoogleTagManager_Helper_Data $helper
 */
$helper = Mage::helper('udevix_google_tag_manager');
if ($helper->isActive() && $helper->isActiveAdwordsConversion()):
    $conversionData = $this->getConversionData();
    ?>
    <?php if ($conversionData !== false) : ?>
    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", function () {
            try {
                dataLayer.push(<?php echo $conversionData ?>);
            }
            catch (err) {
            }
        });
    </script>
<?php endif; ?>
<?php endif; ?>
