<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    tip
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php 
if(!is_null(Mage::registry('share_current_post_data'))){
$currentpost = Mage::registry('share_current_post_data')->getData(); }
else{
	$currentpost = "";
}
if(!empty($currentpost) && count($currentpost) > 0) { ?>

<?php
    $postUrl = $currentpost['address'];
    $imageurl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA). $currentpost['image'];
    $postDescription = $currentpost['short_content'];
    $postTitle = $currentpost['title'];

?>

<!-- Open Graph data -->
<meta property="og:title" content="<?php echo $postTitle ?>" />
<meta property="og:type" content="article" />
<meta property="og:description" content="<?php echo $postDescription ?>" />
<meta property="og:image" content="<?php echo $imageurl ?>" />
<meta property="og:image:width" content="250" />
<meta property="og:image:height" content="250" />
<meta property="og:url" content= "<?php echo $postUrl ?>" />

<!-- Twitter Card data -->
<meta name="twitter:card" content="summary" />
<meta name="twitter:title" content="<?php echo $postTitle ?>" />
<meta name="twitter:description" content="<?php echo $postDescription ?>" />
<meta name="twitter:url" content="<?php echo $postUrl ?>" />
<meta name="twitter:image" content="<?php echo $imageurl ?>" />

<?php } ?>