<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    tip
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $post = $this->getPost(); ?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="postWrapper">
    <?php
    //$postImg = $post->getImage();
    //if (!empty($postImg) && !is_null($postImg)) {
    ?>
    <!-- <div>
         <img src="<?php //echo Mage::getBaseUrl('media') . $post->getImage()       ?>" alt=""/>
     </div> -->
    <?php //}  ?>
    <div class="postTitle">
        <h1><?php echo $post->getTitle(); ?></h1>
<!--        <h3><?php //echo $post->getCreatedTime();       ?></h3>-->
    </div>

    <div class="postContent std"><?php echo $post->getPostContent(); ?></div>
    <?php echo $this->getBookmarkHtml($post) ?>
    <div class="tags">
        <?php echo Mage::helper('blog')->__('Posted'); ?>
        <?php echo $this->__("By"); ?> : <h4 class="poster"><?php echo $post->getUser(); ?></h4>
    </div>

</div>

<!-- Comment Section -->

<?php if ($this->getCommentsEnabled()): ?>
    <div class="commentWrapper">
        <?php $comments = $this->getComment(); ?>
        <div class="commentTitle"><a name="commentBox" ></a>
            <div><?php echo $this->__('Post Comments') ?></div>
        </div>

        <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
        <?php foreach ($comments as $comment) : ?>
            <div class="commentWrapper">
                <div class="commentDetails"><h4 class="username"><?php echo $this->getClearComment($comment->getUser()); ?></h4> <?php echo $this->__("posted on") ?> <?php echo $this->formatDate($comment->getCreatedTime(), Mage::getStoreConfig('blog/blog/dateformat'), true); ?></div>
                <div class="commentContent"><?php echo nl2br($this->getClearComment($comment->getComment())); ?></div>
            </div>
        <?php endforeach; ?>
        <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>


        <?php if ($post->getComments()): ?>
            <div class="postError"><?php echo Mage::helper('blog')->__('Comments are Closed for this post') ?></div>
        <?php else: ?>
            <?php if ($this->getLoginRequired()): ?>
                <?php if ($this->helper('customer')->isLoggedIn()): ?>
                    <form action="" id="postComment" method="post">
                        <div class="fieldset">
                            <h4 class="legend"><?php echo Mage::helper('blog')->__('Submit Comment') ?></h4>
                            <ul class="form-list">
                                <li>

                                    <div class="input-box aw-blog-comment-area">
                                        <label for="comment" class="required"><?php echo Mage::helper('blog')->__('Comment') ?><em>*</em></label><br />
                                        <textarea name="comment" id="comment" title="<?php echo $this->__('Comment') ?>" class="required-entry input-text" style="height:150px;width:100%;" cols="50" rows="5"><?php echo $this->getCommentText(); ?></textarea>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <div class="button-set" style="width:96%">
                            <input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
                            <input name="email" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserEmail()) ?>"/>
                            <input name="user" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserName()) ?>"/>
                            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                            <button class="form-button button" type="submit"><span><span><?php echo Mage::helper('blog')->__('Submit Comment') ?></span></span></button>
                        </div>
                    </form>

                    <script type="text/javascript">
                        var contactForm = new VarienForm('postComment', false);
                    </script>

                <?php else: ?>
                    <p><?php echo Mage::helper('blog')->__('You must be logged in to post a comment.'); ?></p>
                    <p><a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"><?php echo Mage::helper('blog')->__('click here'); ?></a> <?php echo Mage::helper('blog')->__('to log in'); ?></p>
                <?php endif ?>

            <?php else: ?>

                <form action="" id="postComment" method="post">
                    <div class="fieldset">
                        <h4 class="legend"><?php echo Mage::helper('blog')->__('Submit Comment') ?></h4>
                        <ul class="form-list">
                            <li>
                                <div class="input-box">
                                    <label for="name" class="required"><?php echo Mage::helper('blog')->__('Name') ?><em>*</em></label><br />
                                    <input name="user" id="user" value="<?php echo $this->getCommentName(); ?>" title="<?php echo $this->__('Name') ?>" class="required-entry input-text" type="text" />
                                </div>

                                <div class="input-box">
                                    <label for="email" class="required"><?php echo Mage::helper('blog')->__('Email') ?><em>*</em></label><br />
                                    <input name="email" id="email" value="<?php echo $this->getCommentEmail(); ?>" title="<?php echo $this->__('Email') ?>" class="required-entry input-text validate-email" type="text" />
                                </div>

                                <div class="clear"></div>

                                <div class="input-box aw-blog-comment-area">
                                    <label for="comment" class="required"><?php echo Mage::helper('blog')->__('Comment') ?><em>*</em></label><br />
                                    <textarea name="comment" id="comment" title="<?php echo Mage::helper('blog')->__('Comment') ?>" class="required-entry input-text" style="height:150px;width:100%;" cols="50" rows="5"><?php echo $this->getCommentText(); ?></textarea>
                                </div>
                            </li>

                            <?php
                            if (Mage::getStoreConfig('blog/recaptcha/enabled') && !$this->helper('customer')->isLoggedIn()) {
                                ?><li>
                                    <script src='https://www.google.com/recaptcha/api.js'></script><?php
                                    require_once 'recaptcha/recaptchalib-aw.php';

                                    // Get a key from https://www.google.com/recaptcha
                                    $publickey = Mage::getStoreConfig('blog/recaptcha/publickey');
                                    ?></li>
                                <div class="g-recaptcha" data-sitekey="<?php echo $publickey ?>"></div><?php
                            }
                            ?>
                        </ul>
                    </div>
                    <div class="button-set" style="width:96%">
                        <input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
                        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                        <button class="button form-button" type="submit"><span><span><?php echo Mage::helper('blog')->__('Submit Comment') ?></span></span></button>
                    </div>
                </form>

                <script type="text/javascript">
                    var contactForm = new VarienForm('postComment', false);
                </script>
            <?php endif; ?>
        <?php endif; ?>
    </div>
<?php endif; ?>

<?php
// Code for showing products related to this post
$getProductCollection = Mage::helper('blog')->getProductsCollection($post->getData('product_sku'));
if (($_products = $getProductCollection) && count($getProductCollection->getData())):
    ?>
    <div class="widget widget-new-products blog-related-product category-products">
        <div class="widget-title">
            <h2><?php echo $this->__('Blog Related Product') ?></h2>
        </div>
        <div class="widget-products">
            <?php echo $this->getPagerHtml() ?>
            <?php $_columnCount = $this->getColumnCount(); ?>
            <?php $i = 0; ?>        
            <?php $currentDate = Mage::getModel('core/date')->gmtDate('Y-m-d 00:00:00'); ?>        
            <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col-widget">
                <?php foreach ($_products->getItems() as $_product): ?>
                    <?php
                    $productPreOrderDate = $_product->getData('product_date');

                    $extraOptions = '';
                    $productDate = $_product->getProductDate();
                    $productPreOrderText = $_product->getData('product_pre_order_text');
                    if (!is_null($productDate) && !is_null($productPreOrderText)) {
                        $productDate = date('M d Y', strtotime($_product->getProductDate()));
                        $extraOptions = $productPreOrderText . ' ' . $productDate;
                    }
               //     if ($productPreOrderDate > $currentDate || $productPreOrderDate == $currentDate || $productPreOrderDate == null) {
                        ?>
                        <li class="item">
                <!--<div class="product">-->
                            <a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                <?php $_imgSizeWidth = 255; $_imgSizeHeight = 300; ?>
                                <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                     src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSizeWidth, $_imgSizeHeight); ?>"
                                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                            </a>
                            
                            
                            <div class="product-info">                        
                                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_product->getName() ?></a></h2>
                                <?php echo $this->getPriceHtml($_product, true) ?>
                                <?php if (!$_product->getData('hide_shop_button') ) : ?>
                                <div class="actions">
                                    <?php if (!$_product->canConfigure() && $_product->isSaleable()): ?>
                                        <?php
                                         if (!is_null($extraOptions) && !empty($extraOptions)) {
                                            ?>
                                            <button type="button" title="<?php echo $this->quoteEscape($this->__('Shop Now')) ?>" class="button btn-cart" onclick="setLocation('<?php echo Mage::helper('checkout/cart')->getAddUrl($_product, array('extra_options' => $extraOptions)) ?>')"><span><span><?php echo $this->__('Shop Now') ?></span></span></button>
                                        <?php } else { ?>
                                            <button type="button" title="<?php echo $this->quoteEscape($this->__('Shop Now')) ?>" class="button btn-cart" onclick="setLocation('<?php echo Mage::helper('checkout/cart')->getAddUrl($_product) ?>')"><span><span><?php echo $this->__('Shop Now') ?></span></span></button>
                                        <?php } ?>
                                        <!--<a title="<?php //echo $this->quoteEscape($this->__('View More')) ?>" href="<?php //echo $_product->getProductUrl() ?>"class="button btn-cart"><span><span><?php //echo $this->__('View More') ?></span></span></a>-->
                                        <?php elseif ($_product->getTypeId() == 'bundle') : ?>
                                        <form action="<?php echo Mage::helper('checkout/cart')->getAddUrl($_product); ?>" method="post" id="product_addtocart_form_<?php echo $_product->getId() ?>">
                                            <?php if (!empty($extraOptions)) { ?>
                                                <input type="hidden" name="extra_options" id="extra_options" value="<?php echo $extraOptions; ?>" />
                                            <?php } ?>
                                            <?php
                                            $selectionCollection = $_product->getTypeInstance(true)->getSelectionsCollection(
                                                    $_product->getTypeInstance(true)->getOptionsIds($_product), $_product
                                            );
                                            ?>
                                            <?php $saleable = true; ?>
                                            <?php foreach ($selectionCollection as $option) : ?>
                                                <input type="hidden" name="bundle_option[<?php echo $option->option_id; ?>][]" value="<?php echo $option->selection_id; ?>" />
                                                <input type="hidden" name="bundle_option_qty[<?php echo $option->option_id; ?>][]" value="1" />
                                                <?php
        //Stock control for each bundle option
                                                $opt_product = Mage::getModel('catalog/product')->load($option->product_id);
                                                $stocklevel = (int) Mage::getModel('cataloginventory/stock_item')
                                                                ->loadByProduct($opt_product)->getQty();
                                                $productInStock = (int) Mage::getModel('cataloginventory/stock_item')
                                                                ->loadByProduct($opt_product)->getData('is_in_stock');
                                                if ($stocklevel <= 0 || $productInStock == 0){
                                                $saleable = false;}
                                                ?>
                                            <?php endforeach; ?>
                                            <?php if ($saleable): ?>
                                                <button type="button" title="<?php echo $this->__('Shop Now') ?>" class="button" onclick="this.form.submit()"><span><span><?php echo $this->__('Shop Now') ?></span></span></button>
                                                <!--<a title="<?php //echo $this->quoteEscape($this->__('View More')) ?>" href="<?php //echo $_product->getProductUrl() ?>"class="button btn-cart"><span><span><?php //echo $this->__('View More') ?></span></span></a>-->
                                            <?php else: ?>
                                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span> </p>
                                                <!--<a title="<?php //echo $this->quoteEscape($this->__('View More')) ?>" href="<?php //echo $_product->getProductUrl() ?>"class="button btn-cart"><span><span><?php //echo $this->__('View More') ?></span></span></a>-->
                                            <?php endif; ?>
                                        </form>
                                    <?php else: ?>
                                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                        <!--<a title="<?php //echo $this->quoteEscape($this->__('View More')) ?>" href="<?php //echo $_product->getProductUrl() ?>"class="button btn-cart"><span><span><?php //echo $this->__('View More') ?></span></span></a>-->
                                    <?php endif; ?>
                                </div>
                                <?php endif; ?>
                                <?php // if ($_product->getRatingSummary()): ?>
                                    <?php // echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                <?php // endif; ?>
                            </div>
                        <!--</div>-->
                    </li>
                    <?php// } ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>