<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    tip
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if ($posts = $this->getRecent()): ?>
    <?php if (count($posts) > 0): ?>
        <div class="widget-latest">
            <div class="title"><?php echo Mage::helper('blog')->__('LATEST ARTICLES'); ?></div>
            <div class="subtitle subtitleline"><span><?php echo Mage::helper('blog')->__('by our Health Experts'); ?></span></div>
            <ul>
                <?php foreach ($posts as $post): ?>
                    <li>                    
                        <a href="<?php echo $post->getAddress(); ?>" >
                            <?php if (!is_null($post->getImage())) : ?>
                                <img src="<?php echo Mage::getBaseUrl('media') . $post->getImage() ?>" title="<?php echo $post->getTitle(); ?>" alt="<?php echo $post->getTitle(); ?>" width="300px" height="300px"/>
                            <?php else: ?>
                                <img src="<?php echo Mage::getSingleton('catalog/product_media_config')->getBaseMediaUrl() . '/placeholder/' . Mage::getStoreConfig("catalog/placeholder/small_image_placeholder"); ?>" title="<?php echo $post->getTitle(); ?>" alt="<?php echo $post->getTitle(); ?>" width="300px" height="300px"/>
                            <?php endif; ?>
                            <span><?php echo $post->getTitle(); ?></span>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>
<?php endif; ?>