<?php
/**
 * Bridge Batchcode
 *
 * @category      Bridge
 * @package       Bridge_Batchcode
 * @copyright     Copyright (c) 2013 Bridge India. (http://bridge-india.in)
 * @license       http://bridge-india.in/disclaimer/magento
 */
?>
<?php
/**
 * @see Mage_Adminhtml_Block_Sales_Items_Column_Name
 */
?>

<?php if ($_item = $this->getItem()):
 if($_item->getProductType()=='configurable')
{
    $prd_id = Mage::getModel('sales/order_item')->load($_item->getId(),'parent_item_id');
   
}
    ?>
    <h5 class="title"><span id="order_item_<?php echo $_item->getId() ?>_title"><?php echo $this->escapeHtml($_item->getName()) ?></span></h5>
    <div><strong><?php echo $this->helper('sales')->__('SKU') ?>:</strong> <?php echo implode(Mage::helper('catalog')->splitSku($this->escapeHtml($this->getSku()))); ?></div>
    
        
    
        <?php if ($this->getOrderOptions()): ?>
        <dl class="item-options">
            <?php foreach ($this->getOrderOptions() as $_option): ?>
                <dt><?php echo $_option['label'] ?></dt>
                <dd>
                    <?php if (isset($_option['custom_view']) && $_option['custom_view']): ?>
                        <?php echo $this->getCustomizedOptionValue($_option); ?>
                    <?php else: ?>
                        <?php $_option = $this->getFormattedOption($_option['value']); ?>
                        <?php echo $_option['value']; ?><?php if (isset($_option['remainder']) && $_option['remainder']): ?><span id="<?php echo $_dots = 'dots' . uniqid() ?>"> ...</span><span id="<?php echo $_id = 'id' . uniqid() ?>"><?php echo $_option['remainder'] ?></span>
                            <script type="text/javascript">
                                $('<?php echo $_id ?>').hide();
                                $('<?php echo $_id ?>').up().observe('mouseover', function () {
                                    $('<?php echo $_id ?>').show();
                                });
                                $('<?php echo $_id ?>').up().observe('mouseover', function () {
                                    $('<?php echo $_dots ?>').hide();
                                });
                                $('<?php echo $_id ?>').up().observe('mouseout', function () {
                                    $('<?php echo $_id ?>').hide();
                                });
                                $('<?php echo $_id ?>').up().observe('mouseout', function () {
                                    $('<?php echo $_dots ?>').show();
                                });
                            </script>
                        <?php endif; ?>
                    <?php endif; ?>
                            
                </dd>

            <?php endforeach; ?>
            <?php 
    if ($_item['qty_shipped'] > 0) {
        if($_item->getProductType()=='configurable')
{
            if(isset($prd_id))
        {
        echo $this->getLayout()->createBlock('batchcode/adminhtml_batchcode_orderview/')->setData('item_id', $prd_id['item_id'])->toHtml();
        }
}else{
    echo $this->getLayout()->createBlock('batchcode/adminhtml_batchcode_orderview/')->setData('item_id', $_item['item_id'])->toHtml();
}
    }
    ?>
        </dl>
    
    <?php else: ?>  
 
    
    <?php
    if ($_item['qty_shipped'] > 0) {
        
        echo $this->getLayout()->createBlock('batchcode/adminhtml_batchcode_orderview/')->setData('item_id', $_item['item_id'])->toHtml();
        
    }
    ?>
    <?php endif; ?>
    <?php echo $this->escapeHtml($_item->getDescription()) ?>

<?php endif; ?>
