<?php
/**
 * Bridge Batchcode
 *
 * @category      Bridge
 * @package       Bridge_Batchcode
 * @copyright     Copyright (c) 2013 Bridge India. (http://bridge-india.in)
 * @license       http://bridge-india.in/disclaimer/magento
 */
?>
<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?= $this->__('Add new batch') ?></h3></td>
            <td class="a-right">
                <button onclick="editForm.submit()" class="scalable save" type="button"><span>Submit my form</span></button>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">

    <?php
    ?>
    <form id="edit_form_batch" name="edit_form_batch" method="post" action="<?= $this->getUrl('*/*/post') ?>" >
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />

        <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?= $this->__('Batch No') ?> <span class="required">*</span></td>
                    <td class="input-ele"><input class="input-text required-entry" name="batchform[batchno]" /></td>
                </tr>
                <tr>
                    <td class="label"><?= $this->__('Product Id') ?> <span class="required">*</span></td>
                    <td class="input-ele"><input class="input-text required-entry" name="batchform[productid]" /></td>
                </tr>
                <tr>
                    <td class="label"><?= $this->__('Qty') ?> <span class="required">*</span></td>
                    <td class="input-ele"><input class="input-text required-entry" name="batchform[qty]" /></td>
                </tr>
                <tr>
                    <td class="label"><?= $this->__('Status') ?> <span class="required">*</span></td>
                    <td class="input-ele"><input class="input-text required-entry" name="batchform[status]" /></td>
                </tr>
</table>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var editForm = new varienForm('edit_form_batch');
</script>