<?php
/**
 * Bridge Batchcode
 *
 * @category      Bridge
 * @package       Bridge_Batchcode
 * @copyright     Copyright (c) 2013 Bridge India. (http://bridge-india.in)
 * @license       http://bridge-india.in/disclaimer/magento
 */
?>
<?php
$sum='';
$qty_ordered = $this->getData('qty_ordered');
$product_id  = $this->getData('product_id');
$order_item_id =  $this->getData('order_item_id');
$simple_item = Mage::getModel('sales/order_item')->load($order_item_id,'item_id');
$parent_item_id = $simple_item->getParentItemId();

$parent_item = Mage::getModel('sales/order_item')->load($parent_item_id,'item_id');
$product_type = $parent_item->getProductType();
$parent_product_id = $parent_item->getProductId();

$qty_waiting = $qty_ordered;
$batches = $this->getBatchByProduct();

$ptype = array('simple','grouped');

$items = Mage::getModel("sales/order_item")->getCollection()
  ->addFieldToFilter("product_id", array("in" => $product_id))
  ->addFieldToFilter("product_type", array("in" => $ptype));
  
  $order_quantity = 0;
  $order_canceled = 0;
  $order_shipped = 0;
  foreach($items as $_item)
  {
      $item = Mage::getModel("sales/order_item")->load($_item->getId());
$items_parent = Mage::getModel("sales/order_item")->load($item->getParentItemId());
if($items_parent->getProductType()=='configurable')
{
	$item->setQtyShipped($items_parent->getQtyShipped());
}
  $order_quantity+= $item->getQtyOrdered();
  $order_canceled+= $item->getQtyCanceled();
  $order_shipped+= $item->getQtyShipped();
  }
 

  $sum_total = $order_quantity-$order_canceled-$order_shipped;
?>

<?php $count = count($batches); if($count!=''){?><b>BATCHCODE : </b><?php }
$_i = 0; 
foreach ($batches as $batch): ?>

    <?php
    if ($qty_waiting > 0) {
        $selected = 'checked="checked"';
        $qty_waiting = $qty_waiting - $batch->getQty();
    } else {
        $selected = '';
    }
    $sum+= $batch->getQty();
    
    ?>

    
        <input type="checkbox" value="<?php echo $batch->getId(); ?>" name="shipment[batch_id][<?php echo $this->getData('order_item_id'); ?>][]" id="shipment[batch_id]" <?php echo $selected; ?> />&nbsp;<b><?php echo $batch->getBatchNumber(); ?></b>(<?php echo (int) $batch->getQty(); ?>), 

            <?php endforeach;
         
            $condi = Mage::getStoreConfig('cataloginventory/options/can_subtract');
            if($condi==1)
            {
            $prd_id = Mage::getModel('cataloginventory/stock_item')->load($product_id,'product_id');
            $productqty = $prd_id->getQty();
            
            $freeproduct = $productqty+$sum_total;
            $total = $freeproduct-$sum;
            }else {
                $prd_id = Mage::getModel('cataloginventory/stock_item')->load($product_id,'product_id');
                $productqty = $prd_id->getQty();

                $freeproduct = $productqty;
                $total = $freeproduct-$sum;
            }
            
            ?>Non Batch code Product(<?php echo $total; ?>)
            <input type="hidden" value="<?php echo $total; ?>" name="shipment[total][<?php echo $this->getData('order_item_id'); ?>]" /> 

