<?php
/**
 *
 */
?>
<?php
$wellbeingCategory = $this->getChildCategoryCollection();
?>
<?php if (count($wellbeingCategory) > 0): ?>
    <?php foreach ($wellbeingCategory as $category): ?>
        <?php
        $category = Mage::getModel('catalog/category')
                ->setStoreId(Mage::app()->getStore()->getId())
                ->load($category->getId());
        ?>
        <div class="wellbeinglist">
            <div class="wellbeinglist-image">
                <img src="<?php echo Mage::getBaseUrl('media') . 'catalog/category/' . $category->getWellbeingImage(); ?>" alt="<?php echo $category->getName() ?>" title="<?php echo $category->getName() ?>" />
            </div>
            <div class="wellbeinglist-content">
                <h3><?php echo $category->getName(); ?></h3>
                <p><?php echo $category->getShortDescription(); ?></p>
                <a href="<?php echo Mage::getUrl('boxproducts/index/wellbeingview', array('id' => $category->getId())) ?>" alt="" title=""><?php echo $this->__('Find Out More') ?></a>
            </div>
        </div>
    <?php endforeach; ?>
<?php else: ?>
    <?php echo Mage::helper('blog')->__(''); ?>
<?php endif; ?>